### PR TITLE
Exposes subscription mode for consumer

### PR DESCRIPTION
**Pull request by jeantil**
The default subscription mode is `Durable` but some use cases would benefit from a `NonDurable` mode for consumers and are not necessarily compatible with a reader. The consumer property was not exposed through the pulsar4s wrapper hence this proposed change.

### CODE REVIEW

**Comment by jeantil** [comment]
Hello @judu @RemiBardon , 
sorry for the direct ping but the repository doesn't look very active and I'm not sure if anyone has seen my PRs :D
This one is because we need it for the apache/james project pulsar integration. the other one https://github.com/CleverCloud/pulsar4s/pull/570 is for upgrading the pulsar client version to match the pulsar server version hosted on clever cloud :D

thanks !

**Comment by jeantil** [comment]
hello again, any chance to have this merged or do you need me to do additional work ?

**Comment by jeantil** [comment]
hello again @judu @RemiBardon,
any chance to have this merged or do you want me to do additional work ?

thanks 

(also a release would be a nice xmas gift :D )

**Comment by RemiBardon** [comment]
@jeantil I don't work at Clever Cloud anymore, I can't help you.

**Comment by jeantil** [comment]
Hello and happy new year ! 

@judu any chance you could review this very small change and make a release :pray: ?

**Review by judu — APPROVED** [review]

**Comment by judu** [comment]
Thanks for this feature @jeantil !

I'm planning on releasing pulsar4s with it before the end of the week.

**Comment by jeantil** [comment]
thank you ! that's great news :D

**Comment by jeantil** [comment]
Hello, @judu 

I come back to the project on a regular basis and I refrained from doing a direct ping so far but I would really like a release :D

thanks !

**Pull request merged**
